# ❌ High confidence secrets
AWS_SECRET_ACCESS_KEY = "AKIAIOSFODNN7EXAMPLE"
API_KEY = "sk_test_51H8abcXYZ"
PRIVATE_KEY = "-----BEGIN PRIVATE KEY-----ABC123-----END PRIVATE KEY-----"

# REAL PATTERN MATCHES

AWS_ACCESS_KEY = "AKIAIOSFODNN7EXAMPLE"
AWS_SECRET_KEY = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"

GITHUB_TOKEN = "ghp_aBcDeFgHiJkLmNoPqRsTuVwXyZ1234567890"
STRIPE_SECRET = "sk_live_51H8abcXYZ123456789"

MONGO_URI = "mongodb+srv://admin:password123@cluster.mongodb.net/db"

PASSWORD = "SuperSecretPassword@123"
